# Generated by Django 5.2.3 on 2025-06-17 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("universities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "programme",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Bachelor of Science in Computer Science",
                        max_length=200,
                    ),
                ),
                (
                    "year_of_study",
                    models.PositiveIntegerField(
                        blank=True, help_text="e.g., 1, 2, 3, 4, 5", null=True
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        default="avatars/default_avatar.png",
                        null=True,
                        upload_to="avatars/",
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students",
                        to="universities.university",
                    ),
                ),
            ],
        ),
    ]
