# Generated by Django 5.2.3 on 2025-06-17 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("city", models.CharField(max_length=100)),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly version of the name",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="university_logos/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "slug",
                    models.SlugField(help_text="URL-friendly version of the name", max_length=200),
                ),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faculties",
                        to="universities.university",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(help_text="e.g. CS101", max_length=20)),
                ("title", models.CharField(max_length=200)),
                (
                    "year_offered",
                    models.PositiveIntegerField(
                        help_text="Year the course is typically offered, e.g., 1, 2, 3, 4"
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="universities.faculty",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["code"], name="universitie_code_563b88_idx"),
                    models.Index(fields=["title"], name="universitie_title_80be1e_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("faculty", "code"),
                        name="unique_course_code_per_faculty",
                    ),
                    models.UniqueConstraint(
                        fields=("faculty", "title"),
                        name="unique_course_title_per_faculty",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="faculty",
            constraint=models.UniqueConstraint(
                fields=("university", "slug"), name="unique_faculty_slug_per_university"
            ),
        ),
        migrations.AddConstraint(
            model_name="faculty",
            constraint=models.UniqueConstraint(
                fields=("university", "name"), name="unique_faculty_name_per_university"
            ),
        ),
    ]
